import type { Metadata } from 'next'
import { LegalPage, Section, Callout, List } from '@/components/legal/legal-page'
import { LEGAL_ENTITY, BRAND } from '@/lib/company'

export const metadata: Metadata = {
  title: 'Terms of Service — SocialCalcs',
  description: 'The terms governing your use of SocialCalcs.',
}

const linkStyle = { color: 'var(--accent)', fontWeight: 600 } as const

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="July 16, 2026"
      intro={
        <>
          These Terms of Service (the &ldquo;Terms&rdquo;) are a binding agreement between you and{' '}
          <strong>{LEGAL_ENTITY}</strong>, an Ontario corporation operating as {BRAND} (&ldquo;{BRAND}&rdquo;,
          &ldquo;we&rdquo;, &ldquo;us&rdquo;). {BRAND} is a product of {LEGAL_ENTITY}; it is not a separate
          company. These Terms govern your access to and use of the {BRAND} website, application,
          calculators, embeds, APIs, and related services (together, the &ldquo;Service&rdquo;). Please read them
          carefully.
        </>
      }
    >
      <Section n={1} heading="Acceptance of these Terms">
        <p>
          By creating an account, accessing, or using the Service, you agree to these Terms. If you do not agree, do
          not use the Service. If you are entering into these Terms on behalf of a company, brokerage, or other
          organization, you represent that you have authority to bind that entity, and &ldquo;you&rdquo; means that
          entity.
        </p>
        <p>
          The Service is offered to businesses and licensed professionals for business purposes. It is not intended
          for personal, family, or household use.
        </p>
      </Section>

      <Section n={2} heading="Calculators produce estimates, not advice">
        <Callout>
          <strong>
            The calculators, figures, projections, and PDF reports generated through the Service are illustrative
            estimates only.
          </strong>{' '}
          They are not financial, mortgage, lending, investment, tax, legal, or accounting advice, and they are not
          an offer, pre-approval, commitment to lend, or guarantee of any rate, term, or outcome. Actual results
          will differ. Any person relying on an output should consult a licensed professional and confirm the
          figures independently.
        </Callout>
        <p>
          Outputs depend entirely on the inputs and assumptions you and your site visitors provide. We do not verify
          those inputs, and we do not warrant that any calculation, formula, rate, or projection is accurate,
          current, complete, or suitable for any particular purpose or jurisdiction.
        </p>
        <p>
          <strong>You are solely responsible for reviewing every calculator you publish or embed</strong>, for
          confirming that its logic, assumptions, and disclosures are appropriate for your clients and your
          regulator, and for the consequences of any figure presented to any person under your name or brand.
        </p>
      </Section>

      <Section n={3} heading="Your professional and regulatory responsibilities">
        <p>
          You are solely responsible for your own licensing, registration, and regulatory compliance, including any
          requirements of the Financial Services Regulatory Authority of Ontario (FSRA), any provincial or
          territorial mortgage, real estate, insurance, or securities regulator, and any brokerage, association, or
          professional body you belong to.
        </p>
        <p>
          Anything you publish through the Service is your advertising and your communication. We do not review it
          for regulatory compliance and we make no representation that any page, calculator, report, or template is
          compliant with any law or regulator in any jurisdiction. You agree that:
        </p>
        <List
          items={[
            'Any licence number, title, designation, or credential you display is accurate and current, and you are entitled to display it.',
            'Your pages, calculators, embeds, and reports meet all disclosure, disclaimer, and advertising rules that apply to you.',
            'You have any consent, authority, or approval your brokerage or regulator requires before publishing.',
            'You will not present the Service, or anything generated by it, as advice from SocialCalcs.',
          ]}
        />
      </Section>

      <Section n={4} heading="Leads, personal information, and anti-spam law">
        <p>
          The Service captures personal information from your site visitors and prospective clients
          (&ldquo;Leads&rdquo;). As between you and us,{' '}
          <strong>you are the party responsible for that personal information</strong>. We process it on your behalf
          and on your instructions in order to provide the Service.
        </p>
        <Callout>
          <strong>You are responsible for compliance with Canada&apos;s Anti-Spam Legislation (CASL)</strong> and any
          other anti-spam, telemarketing, or privacy law that applies to you, including obtaining and maintaining a
          valid consent basis before sending any commercial electronic message to a Lead, identifying yourself
          correctly, and honouring unsubscribe requests promptly.
        </Callout>
        <p>You further represent and warrant that:</p>
        <List
          items={[
            'You have all rights, consents, and legal bases required to collect, use, and disclose Lead information through the Service, and to have us process it for you.',
            'Your own privacy policy accurately describes your collection and use of Lead information.',
            'You will respond to any access, correction, deletion, or withdrawal-of-consent request from a Lead as required by applicable privacy law.',
            'You will not upload or collect sensitive personal information — including government identifiers, full financial account numbers, or health information — through the Service.',
          ]}
        />
        <p>
          Our handling of personal information is described in our{' '}
          <a href="/privacy" style={linkStyle}>
            Privacy Policy
          </a>
          .
        </p>
      </Section>

      <Section n={5} heading="Accounts and security">
        <p>
          You must provide accurate registration information and keep it current. You are responsible for all
          activity under your account and for keeping your credentials confidential. Notify us promptly at{' '}
          <a href="mailto:support@socialcalcs.com" style={linkStyle}>
            support@socialcalcs.com
          </a>{' '}
          if you suspect unauthorized access. You may not share, sell, or transfer your account, and you may not
          allow anyone else to use a seat licensed to you.
        </p>
      </Section>

      <Section n={6} heading="Your content">
        <p>
          You retain ownership of the content you upload or create through the Service, including your text, logos,
          images, calculator configurations, and Lead data (&ldquo;Your Content&rdquo;). You grant us a worldwide,
          non-exclusive, royalty-free licence to host, store, reproduce, adapt, and display Your Content solely to
          operate, secure, support, and improve the Service.
        </p>
        <p>
          You represent that you own or have the rights to Your Content and that it does not infringe anyone&apos;s
          rights or violate any law. We may remove any content that we reasonably believe violates these Terms or
          exposes us or any third party to liability.
        </p>
      </Section>

      <Section n={7} heading="Acceptable use">
        <p>You will not, and will not permit anyone else to:</p>
        <List
          items={[
            'Use the Service to mislead, defraud, or make false or unsubstantiated claims about rates, approvals, savings, or outcomes.',
            'Present calculator outputs as guaranteed, approved, or binding.',
            'Impersonate any person or misrepresent your licensing, credentials, or affiliation.',
            'Upload unlawful, infringing, defamatory, or malicious content.',
            'Reverse engineer, scrape, resell, or create a competing service from the Service.',
            'Interfere with or place unreasonable load on the Service, or attempt to bypass any security or usage limit.',
            'Use the Service to send messages that violate CASL or any other anti-spam law.',
          ]}
        />
      </Section>

      <Section n={8} heading="Plans, fees, and cancellation">
        <p>
          Paid plans are billed in advance on a recurring monthly or annual basis and{' '}
          <strong>renew automatically</strong> at the then-current rate until cancelled. Fees are in Canadian dollars
          unless stated otherwise and are exclusive of applicable taxes, which you are responsible for.
        </p>
        <List
          items={[
            'You may cancel at any time. Cancellation takes effect at the end of your current billing period.',
            'Except where required by law, fees already paid are non-refundable, and we do not provide partial-period refunds or credits for unused time.',
            'We may change pricing on reasonable notice. Changes take effect at your next renewal.',
            'If payment fails or is overdue, we may suspend or downgrade your account.',
            'Free plans and trials are provided as-is and may be modified, limited, or discontinued at any time.',
          ]}
        />
      </Section>

      <Section n={9} heading="Availability and changes to the Service">
        <p>
          We do not guarantee that the Service will be uninterrupted, error-free, or available at any particular
          time. We may modify, suspend, or discontinue any part of the Service, including any calculator or feature,
          at any time. We may perform maintenance without notice. We are not liable for any unavailability.
        </p>
      </Section>

      <Section n={10} heading="Third-party services">
        <p>
          The Service relies on third-party providers for hosting, storage, payment processing, and email delivery,
          and may link to or interoperate with third-party sites and tools. We do not control those providers and are
          not responsible for their acts, omissions, availability, or content.
        </p>
      </Section>

      <Section n={11} heading="Intellectual property">
        <p>
          The Service, including its software, calculator engines, report templates, design, and the SocialCalcs name
          and marks, is owned by {LEGAL_ENTITY} and protected by intellectual property law. Subject to these Terms, we
          grant you a limited, revocable, non-exclusive, non-transferable licence to use the Service for your own
          business purposes. All rights not expressly granted are reserved. Any feedback you give us may be used
          without restriction or compensation.
        </p>
      </Section>

      <Section n={12} heading="Disclaimer of warranties">
        <Callout>
          <strong>
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo;, WITHOUT WARRANTY OF ANY KIND.
          </strong>{' '}
          To the fullest extent permitted by law, we disclaim all express, implied, statutory, and collateral
          warranties and conditions, including any implied warranty of merchantability, fitness for a particular
          purpose, durability, title, non-infringement, accuracy, or quiet enjoyment.
        </Callout>
        <p>
          Without limiting the above, we do not warrant that the Service will meet your requirements, that it will be
          secure, uninterrupted, timely, or error-free, that defects will be corrected, or that any calculation,
          estimate, projection, rate, or report produced through the Service is accurate, complete, current, or
          suitable for any purpose or jurisdiction.
        </p>
      </Section>

      <Section n={13} heading="Limitation of liability">
        <Callout>
          <strong>
            To the fullest extent permitted by law, our total aggregate liability arising out of or relating to these
            Terms or the Service will not exceed the greater of (a) the fees you actually paid us for the Service in
            the twelve (12) months immediately before the event giving rise to the claim, or (b) one hundred Canadian
            dollars (CAD $100).
          </strong>
        </Callout>
        <p>
          To the fullest extent permitted by law, we will not be liable for any indirect, incidental, special,
          consequential, exemplary, or punitive damages, or for any loss of profits, revenue, business, goodwill,
          clients, leads, opportunity, savings, or data, or for any cost of substitute services — even if we have
          been advised of the possibility of such damages, and regardless of the theory of liability.
        </p>
        <p>
          <strong>
            We are not liable for any decision made, action taken, or loss suffered by you, your clients, your Leads,
            or any other person in reliance on any calculation, estimate, projection, or report generated through the
            Service.
          </strong>
        </p>
        <p>
          These limitations apply to all claims, whether in contract, tort (including negligence), strict liability,
          statute, or otherwise, and survive any failure of essential purpose of any limited remedy. Some limitations
          may not apply to the extent prohibited by applicable law; in that case, our liability is limited to the
          least extent permitted.
        </p>
      </Section>

      <Section n={14} heading="Indemnity">
        <p>
          You will defend, indemnify, and hold harmless {LEGAL_ENTITY} and its directors, officers, employees, and agents
          from and against any claim, demand, action, proceeding, loss, liability, damage, fine, penalty, and expense
          (including reasonable legal fees) arising out of or relating to:
        </p>
        <List
          items={[
            'Your Content, your pages, your calculators, your embeds, or your reports.',
            'Your use or misuse of the Service, or use by anyone using your account.',
            'Any figure, estimate, or report you presented to any person, and any reliance on it.',
            'Your breach of these Terms or of any representation or warranty in them.',
            'Your violation of any law or regulator requirement, including CASL, privacy law, and any licensing, advertising, or disclosure rule that applies to you.',
            'Any claim by a Lead, client, brokerage, or regulator relating to your activities.',
          ]}
        />
      </Section>

      <Section n={15} heading="Suspension and termination">
        <p>
          You may stop using the Service and close your account at any time. We may suspend or terminate your access
          immediately, with or without notice, if we reasonably believe you have breached these Terms, created risk or
          legal exposure for us or any third party, or failed to pay.
        </p>
        <p>
          On termination your licence ends and we may delete Your Content after a reasonable period. Export your data
          before you cancel. Sections 2, 4, 6, 11, 12, 13, 14, 16, and 17 survive termination.
        </p>
      </Section>

      <Section n={16} heading="Governing law and disputes">
        <p>
          These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable in
          it, without regard to conflict-of-laws rules. You and we irrevocably submit to the exclusive jurisdiction of
          the courts of the Province of Ontario, and you waive any objection to venue in Toronto, Ontario.
        </p>
        <p>
          Any claim must be brought within one (1) year after it arises, or it is permanently barred, except where
          applicable law does not permit such a limit.
        </p>
      </Section>

      <Section n={17} heading="Changes to these Terms">
        <p>
          We may update these Terms from time to time. If we make a material change, we will take reasonable steps to
          notify you, such as by email or an in-app notice. Changes take effect on the date posted above. Your
          continued use of the Service after that date means you accept the updated Terms.
        </p>
      </Section>

      <Section n={18} heading="General">
        <p>
          These Terms, together with our Privacy Policy, are the entire agreement between you and us about the
          Service. If a provision is found unenforceable, it will be limited or severed to the minimum extent
          necessary and the rest stays in force. Our failure to enforce a provision is not a waiver of it. You may not
          assign these Terms without our written consent; we may assign them, including in connection with a merger,
          financing, or sale of assets. Nothing in these Terms creates a partnership, joint venture, agency, or
          employment relationship. Neither party is liable for delays caused by events beyond its reasonable control.
        </p>
      </Section>

      <Section n={19} heading="Contact">
        <p>
          Questions about these Terms:{' '}
          <a href="mailto:support@socialcalcs.com" style={linkStyle}>
            support@socialcalcs.com
          </a>
          .
        </p>
      </Section>
    </LegalPage>
  )
}
